### ISSUE TITLE
Wrong behavior (?) with a supported attack

### ISSUE THREAD

**Issue by felixludos** [aparkins/pydip#5]
Thanks for the well-designed package!

I did run into a strange situation that is somehow missed by the DATC suite (possibly because of the combination of using fleets and troops). I believe the resolution of the example below is incorrect as the troop attacking Bulgaria should be successful, despite its support getting attacked.

```
from pydip.player.unit import Unit, UnitTypes
from pydip.test.command_helper import CommandType, CommandHelper
from pydip.test.player_helper import PlayerHelper
from pydip.test.turn_helper import TurnHelper

helper = TurnHelper([
        PlayerHelper('Italy', [
            CommandHelper(CommandType.MOVE, UnitTypes.FLEET, 'Bulgaria South Coast', 'Greece Coast'),
        ]),
        PlayerHelper('Austria', [
            CommandHelper(CommandType.MOVE, UnitTypes.TROOP, 'Serbia', 'Bulgaria'),
            CommandHelper(CommandType.SUPPORT, UnitTypes.TROOP, 'Greece', 'Serbia', 'Bulgaria'),
        ])
    ])

result = helper.resolve()
assert result == {
    'Austria': {
        Unit(UnitTypes.TROOP, 'Serbia'): None,
        Unit(UnitTypes.TROOP, 'Greece'): None,
    },
    'Italy': {
        Unit(UnitTypes.FLEET, 'Bulgaria South Coast'): None,
    },
}
```

**Comment by aparkins** [comment]
Ah, you are correct with that.

There is a _similar_ test in the DATC, but the version I've implemented checks only for fleets moving with relation to one another. This scenario involves fleets and troops interacting, and I suspect this test is showing a bug with identifying coasts as the same territory as the land territory they are associated with. There were a handful of other similar bugs I had to correct while doing the initial implementation, this one must have slipped past.

I'm looking into a fix now.

**Comment by taparkins** [comment]
@felixludos:

This issue should be resolved on the most recent commit. I've cleaned up a handful of locations that coast / land territory checks were being missed, and this should resolve a handful of issues that have been hanging around for a while now. The commit with these changes is visible [here](https://github.com/aparkins/pydip/commit/6144170e619af44d20f4eec69a2a5730553d56e3).

I've also added your test case (as well as a variant that swaps the troop / fleet roles), and also caught an incorrectly implemented DATC test that was being covered up due to this bug. Thanks for writing that out!
